/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    GrowthChart: typeof import('./src/components/GrowthChart.vue')['default']
    MemberCard: typeof import('./src/components/MemberCard.vue')['default']
    RecordForm: typeof import('./src/components/RecordForm.vue')['default']
    RecordList: typeof import('./src/components/RecordList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
  }
}
